# Generated by Django 5.2.15 on 2026-06-15 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('products', '0005_alter_category_options_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreport',
            name='top_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
