# Generated by Django 5.2.15 on 2026-06-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Mac GunJon - Is Bot', max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, default='+8809638089695', max_length=20)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('discord_url', models.URLField(blank=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=50)),
                ('meta_title', models.CharField(blank=True, default='Mac GunJon - Is Bot', max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('stripe_public_key_display', models.CharField(blank=True, help_text='Display only, actual key in .env', max_length=255)),
                ('footer_text', models.TextField(blank=True)),
                ('about_text', models.TextField(blank=True)),
                ('is_singleton', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
