# Generated by Django 5.2.15 on 2026-06-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='e.g., 50+, 1K+, 99%, 24/7', max_length=20)),
                ('label', models.CharField(help_text='e.g., Products, Happy Customers', max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=50)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('orders', 'Orders'), ('payments', 'Payments'), ('delivery', 'Delivery'), ('products', 'Products'), ('account', 'Account'), ('general', 'General')], default='general', max_length=20)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ordering', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomePageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero Banner'), ('ecosystem', 'Ecosystem Card'), ('how_it_works', 'How It Works Step')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=50)),
                ('color', models.CharField(default='#3b82f6', help_text='Hex color', max_length=7)),
                ('cta_text', models.CharField(blank=True, max_length=100)),
                ('cta_url', models.CharField(blank=True, max_length=200)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Home page sections',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='e.g., E-commerce Owner', max_length=150)),
                ('quote', models.TextField()),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('avatar_image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('avatar_color', models.CharField(default='#3b82f6', help_text='Hex color for avatar fallback', max_length=7)),
                ('is_featured', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ordering', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='e.g., 2024', max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=50)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_founded_year',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_mission_points',
            field=models.JSONField(blank=True, default=list, help_text='List of mission commitment strings'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_mission_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_mission_title',
            field=models.CharField(blank=True, default='Our Mission', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_story_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_story_title',
            field=models.CharField(blank=True, default='Built for the digital age', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_hours',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object with day ranges as keys and hours as values'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.TextField(blank=True, help_text='Google Maps embed URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, default='support@macgunjon.com', max_length=254),
        ),
    ]
