# Generated by Django 5.2.15 on 2026-06-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_companystat_faq_homepagesection_testimonial_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EcosystemCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=300)),
                ("icon", models.CharField(blank=True, default="layout", help_text="Lucide icon name", max_length=50)),
                ("color", models.CharField(default="#3b82f6", help_text="Hex color", max_length=7)),
                ("ordering", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Ecosystem cards",
                "ordering": ["ordering"],
            },
        ),
        migrations.CreateModel(
            name="HomePageBanner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=200)),
                ("chip_text", models.CharField(blank=True, default="100% Instant Digital Delivery", max_length=100)),
                ("cta_text", models.CharField(blank=True, default="Browse Products", max_length=100)),
                ("cta_url", models.CharField(blank=True, default="products:product_list", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Home page banners",
            },
        ),
    ]
