# Generated by Django 5.2.15 on 2026-06-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_ecosystemcard_homepagebanner"),
    ]

    operations = [
        migrations.AddField(
            model_name="ecosystemcard",
            name="page",
            field=models.CharField(
                choices=[("home", "Home Page"), ("about", "About Page")], default="home", max_length=10
            ),
        ),
    ]
