# Generated by Django 5.2.15 on 2026-06-15 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_category_icon_product_whats_included_productfeature"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="consent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="consent_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="products/files/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "zip",
                            "pdf",
                            "rar",
                            "jpg",
                            "png",
                            "mp4",
                            "mov",
                            "csv",
                            "json",
                            "py",
                            "js",
                            "css",
                            "html",
                            "txt",
                            "docx",
                            "xlsx",
                        ]
                    )
                ],
            ),
        ),
    ]
